- job:
    name: devstack-plugin-kafka-tempest-full
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-full-kafka/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-full-kafka/post.yaml
    timeout: 10800
    required-projects:
      - openstack/devstack-gate
      - openstack/devstack-plugin-kafka
      - openstack/tempest

- project:
    check:
      jobs:
        - openstack-tox-bashate
        - devstack-plugin-kafka-tempest-full:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - oslo.messaging-src-dsvm-full-kafka-default:
            voting: false
        - oslo.messaging-src-dsvm-full-kafka-default-centos-7:
            voting: false
    gate:
      jobs:
        - openstack-tox-bashate
